site_name: Kawa dla szefa - tutorial
nav:
  - Start: index.md
  - Wprowadzenie: wprowadzenie.md
  - Rodzaje kawy: rodzaje.md
  - Dodatki: zczympodac.md
  - Sposoby parzenia: sposoby.md
theme:
  name: bootstrap386